# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

ISENSE_PATH=/home/amaxilatis/sdks/Collector

# all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=collector.cpp
export BIN_OUT=collector

include ../Makefiles/Makefile
